### ISSUE TITLE
Anonymous Compound Access

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#102]
**As a** anonymous user
**I want** to be able to read all contents of the compound api
**So that** I don't have to login to access the data

In general, GET requests in the Compound API should not require authentication

**Acceptance Criteria**
When I can perform GET on all the URL resources below including the paginated lists, the detail resources obtained by appending the ID to the URL, and any filtering/search functions.
http://api.chemreg.epa.gov/
http://api.chemreg.epa.gov/defined-compounds/
http://api.chemreg.epa.gov/ill-defined-compounds/
http://api.chemreg.epa.gov/query-structure-types/

**Comment by kdionisio** [comment]
request may be covered by #37 and #38
