### ISSUE TITLE
Defined-compound posts takes only 1 structural string.

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#103]
**As a** user
**I want** to be prevented me from submitting more than one structure string in a post to defined-compound
**So that** I can't try to register conflicting data

**Request Example**
`POST https://api.chemreg.epa.gov/`

**Acceptance Criteria**
When post to the defined-compound with more than one structural string (smiles, molfile_v3000, molfile_v2000), the request will be rejected and the user informed that only one structural string can be submitted.  Also, if no structural string is submitted, the error message should indicate that 1 structural string is required (but not that a molfile_v3000 is required as a smiles is fine).

**Comment by kdionisio** [comment]
request may be covered by #37 and #38

**Comment by mcovalt** [comment]
This behavior is already included. The following tests demonstrate the functionality:

1. [Test at least one structure is required](https://github.com/Chemical-Curation/chemcurator_django/blob/32b729bdc5bf51ebc698f9cfbe9f44a769fab875/chemreg/compound/tests/test_validators.py#L25-L38)
2. [Test that no more than one structure is allowed](https://github.com/Chemical-Curation/chemcurator_django/blob/32b729bdc5bf51ebc698f9cfbe9f44a769fab875/chemreg/compound/tests/test_validators.py#L55-L79)
