### ISSUE TITLE
substance relationship model

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#138]
**As a** Admin
**I want** to be able to store a substance relationship
**So that** I can link two substances together

A substance relationship consists of:
substance1 - a substance fk for the first member in the relationship (required)
substance2 - a substance fk for the secondary member in the relationship (required)
relationship type - a relationship-type fk for the type of relationship between the two (required)
source - a fk to a source controlled vocabulary for the source type from which this data was derived (required)
qc_notes - a string (1024 max) (optional)

**Acceptance Criteria**
A test to show when a relationship is created it works properly...

**Comment by mcovalt** [comment]
Closed via #184
