### ISSUE TITLE
Name resolution

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#142]
**As a** researcher
**I want to** be able to able to find a substance using a name or casrn
**So that** I can find the chemical I am interested in

`GET https://api.chemreg.epa.gov/search?identifer=$$$$$$$`

Acceptance Criteria:
- An endpoint exists that allows me to search for an identifier.  
- that endpoint being a different and complicated function spanning multiple resources in our CRUD API should exist as a separate microservice
- as a separate microservice and following the concept of encapsulation, the resolution app should have a separate data source that is not coupled at the database level to our CRUD database
- If the searched identifier matches a substance.preferred_name, substance.display_name, substance.casrn, a list of the dtxsids for those substances are returned.
- Separate repo and docker file
- New datastore

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/14nQEpLFfohI6YAUUBUKuTWjvsyh5D8Bl/view?usp=sharing)

**Comment by mwfrost** [comment]
I have not built factories for populating the seed data yet, so please use the two PUT requests in this collection to seed it:
https://www.getpostman.com/collections/8011f655ac5d454f0af2

Once the records are in the `compounds` table you can see the results at these URLs:

http://localhost:5000/api/v1/resolver?identifier=1050-79-9
http://localhost:5000/api/v1/resolver?identifier=Hydrogen+peroxide
