### ISSUE TITLE
Name hit scoring and hit message

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#144]
**As a** researcher
**I want to** be able to able to order the hits for a name based on the quality and type of the identifier
**So that** I can find the chemical I am interested in

`GET https://api.chemreg.epa.gov/search?identifer=$$$$$$$`

Acceptance Criteria:
- Instead of just returning a list of substances, the search should score the potential hits and rank them so the first member of the list is the highest scoring hit.  
- The score for a hit against a synonym.identifier should be the associated synonym_quality.score_weight + synonym_type.score_modifier
- The score for hits against the substance.preferred_name, substance.display_name, substance.casrn should be 1.0
- The returned list should include the hit score and a description of the type hit (e.g. "Matched Preferred_Name", "Matched Valid Alternate CAS-RN", "Matched Ambiguous Name", "Matched Valid PCS-Code").

**Comment by debboutr** [comment]
[Audio from ticketing...](https://drive.google.com/file/d/1pgDXqoV4k8-4G9b7AdGZB1Cso5XoWivg/view?usp=sharing)

**Comment by mwfrost** [comment]
Maybe the distinction between "matching" and "ranking" offers a clean line along which to split this ticket?

From the PostgreSQL docs:

https://www.postgresql.org/docs/13/textsearch-intro.html#TEXTSEARCH-MATCHING

https://www.postgresql.org/docs/13/textsearch-controls.html#TEXTSEARCH-RANKING

**Comment by mwfrost** [comment]
@cmgrulke Chris, we are thinking about how to divide this ticket, and we need some clarification.

Does a _partial_ string match against  `substance.preferred_name`, `substance.display_name`, or `substance.casrn` yield a result score of 1.0? That would mean a lot of 1.0 results for a search on "hydrogen."

Similarly, does a partial match on a synonym score the same as a full-string match?

**Comment by mwfrost** [comment]
After discussing this on Slack, the product owner confirmed that partial string matches will not count as matches for the purposes of this ticket.

**Comment by mwfrost** [comment]
*Questions that may need to be resolved before finalizing the PR:*

- The acceptance criteria include three fields that can all score 1.0, but no tiebreaking logic. 
- The resources inside the list appear to sort by the `searchscore` attribute as requested, but _I don't know why..._ A test confirms that the order of two records follows the `searchscore`, not the DTXSID.
