### ISSUE TITLE
synonym/name uniqueness validation

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#145]
**As a** curator
**I want to** be able to able to validate that synonyms falling into certain synonym_qualities are unique
**So that** we can reduce the ambiguity of name-chemical associations

`POST https://api.chemreg.epa.gov/synonyms`
`PATCH https://api.chemreg.epa.gov/synonyms`
`POST https://api.chemreg.epa.gov/substances`
`PATCH https://api.chemreg.epa.gov/substances`

**Acceptance Criteria:**
- When a substance.preferred_name, substance.display_name, substance.casrn or synonym.identifier (for a synonym with a synonym_quality.is_restrictive = true) is stored, the application verifies that it is unique across all those fields in the database (ignoring synonym.identifier values for synonyms with synonym_quality.is_restrictive = false).
- If the error message should be "The identifier '$(submitted identifier value)' is not unique in restrictive name fields"

**Comment by mcovalt** [comment]
Per discussion during grooming: we need to put indexes on the columns we are checking against.

**Comment by mwfrost** [comment]
More grooming details: 
The restriction should work in both directions. If a synonym has been assigned a restrictive type, the user should not be allowed to add a new `synonym.identifier` that already exists in `substance.preferred_name`, `substance.display_name`, or `substance.casrn`

**Comment by mwfrost** [comment]
See #146 - the `is_restrictive` boolean cannot be set to True if the uniqueness is violated.

**Comment by debboutr** [comment]
after discussion it appears that the `"preferred_name","display_name", "casrn"` fields already have an Index on them w/ the `unique=True` attr in the field. 

There will still be the need to put an Index on the `Synonym.identifier` field, but @mwfrost and I have decided to do it in another ticket that will address the Indexes needed on the CommonInfo model and potentially others.

**Comment by debboutr** [comment]
@cmgrulke to be sure... upon the creation of a new substance, each of the fields will be unique among themselves, i.e, the `"preferred_name","display_name","casrn"?? So the `"display_name"` and the `"preferred_name"` can't be the same w/in the record?

**Comment by cmgrulke** [comment]
Hmmm, good catch... So the business process here is not clear to me yet.  We have been avoiding special characters in preferred names because they have traditionally caused issues when exporting and sending them out to research partners.  Display names are the names we want to display on our web sites and can include special characters.  Display name should == preferred name in 95% of cases.  I think they way I want it to work will be to make display name not required and whenever display name is null have the api export the preferred name as the display name.  This needs to be put in a new ticket...

To answer your question, I do not want display name and preferred name to be stored as identical.
