### ISSUE TITLE
Substance name field regexp validations

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#151]
**As a** curator
**I want to** be restricted from creating substance.preferred_names, substance.display_names, and substance.casrns that do not conform to specific regular expressions
**So that** I can be sure the formatting of the values in these fields are correct

`POST https://api.chemreg.epa.gov/substances`
`PATCH https://api.chemreg.epa.gov/substances`

**Acceptance Criteria:**
- When an substance is created or updated, validate casrn, display_name, and preferred_name using regexpessions
-- Preferred Name Regexp: ^[ a-zA-Z0-9\-=<>:\.\,^_%&/\{\}\[\]\(\)\+\?=]+$
-- Display name regexp: ^[ a-zA-Z0-9\-=<>:\.\,^_%&/\{\}\[\]\(\)\+\?=]+$
-- Casrn regexp: ^[0-9]{2,7}-[0-9]{2}-[0-9]$
- If they are not valid, an error message of "The proposed ${"Preferred_Name|Display_Name|CAS-RN} '${value}' does not conform to the regexp ${relevant regexp}" is returned

**Comment by michael-barbour** [comment]
#152 creates a function `chemreg.common.validators.validate_casrn_format()` which is being used to validate formatting.  This isn't required to use, but could be helpful.

**Comment by michael-barbour** [comment]
Possible regex for CAS-RN.

[^[0-9]{2,7}-[0-9]{2}-[0-9]$](https://pythex.org/?regex=%5E%5B0-9%5D%7B2%2C7%7D-%5B0-9%5D%7B2%7D-%5B0-9%5D%24&test_string=1234567-89-5&ignorecase=0&multiline=0&dotall=0&verbose=0)

**Comment by michael-barbour** [comment]
After talking to @cmgrulke we landed on `^[a-zA-Z0-9 \-=<>:.,^%&/{}[\]()+?=]{3,}$` as the name regex.  This eliminates special characters and sets a minimum of at least 3 characters.
