### ISSUE TITLE
CAS-RN Checksum validation

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#152]
**As a** curator
**I want to** be restricted from storing cas-rns that do not meet checksum requirements
**So that** I can be sure the values in these fields that do not meet checksum are rejected

`POST https://api.chemreg.epa.gov/substances`
`PATCH https://api.chemreg.epa.gov/substances/{id}`
`POST https://api.chemreg.epa.gov/synonyms`
`PATCH https://api.chemreg.epa.gov/synonyms/{id}`

**Acceptance Criteria:**
- add a boolean flag to the synonym_type entity named "is_casrn"
- When an substance or synonym is created or updated, validate the substance.casrn and any synonym.identifier values associated with a synonym_type.is_casrn = true meet checksum.
- If a submitted casrn does not meet checksum, reject the POST/PATCH with message "Provided CAS-RN does not meet checksum requirements.

**Comment by cmgrulke** [comment]
The checksum calculation procedure is described on wikipedia here: https://en.wikipedia.org/wiki/CAS_Registry_Number#Format

**Comment by mwfrost** [comment]
This might require changing the name of the `compute_checksum` method in `chemreg.common.utils`, or maybe adding an argument for the type of checksum.

**Comment by michael-barbour** [comment]
There seem to be other rules for formatting on this page.  Would you like those enforced too?

[^\d{2,7}-\d{2}-\d$](https://pythex.org/?regex=%5E%5Cd%7B2%2C7%7D-%5Cd%7B2%7D-%5Cd%24&test_string=1234567-89-5&ignorecase=0&multiline=0&dotall=0&verbose=0)

> A CASRN is separated by hyphens into three parts, the first consisting from two up to seven digits, the second consisting of two digits, and the third consisting of a single digit serving as a check digit. This current format gives CAS a maximum capacity of 1,000,000,000 unique identifiers.

**Comment by debboutr** [comment]
My take on this is that a `substance.casrn` will ALWAYS be validated, but for any Synonym that is associated with a substance that has a SynonymType w/ `is_casrn=True` each `synonym.identifier` field needs to be validated as a CASRN also.

**Comment by michael-barbour** [comment]
> My take on this is that a `substance.casrn` will ALWAYS be validated, but for any Synonym that is associated with a substance that has a SynonymType w/ `is_casrn=True` each `synonym.identifier` field needs to be validated as a CASRN also.

This reading makes a lot more sense.  Thanks!

**Comment by cmgrulke** [comment]
Yes, the reading that substance.casrn is always validated is my intention.  The syonynym identifier is validated only if the is_casrn==true.
