### ISSUE TITLE
Query CAS-RN corrections

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#156]
As a *user*
I want *numeric identifiers when queried to also be queried as CAS-RNs*
So that *if I do not properly stored casrns in casrn format, I can still search for it effectively*

`GET https://api.chemreg.epa.gov/search?identifer=$$$$$$$`

it is common to see the cas-rn "50-00-0" shown as "50000" or "00050000" or "00050-00-0" or "0000050-00-0".  These all need to resolve.

Acceptance Criteria:
The misformatted CASRNs above do identify 50-00-0 as a hit.
Hits found requiring these correction have their score penalized by 0.25 points.

**Comment by jtumkur** [comment]
- Resolve entry of 0 and "-" are primary issues. This is the main purpose of this ticket. 
- To store the CAS Rn
