### ISSUE TITLE
Source Substance (Record) Model

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#175]
**As a** product owner
**I want** to be able to store all the identifiers associated with a member of a source list
**So that** I can use those identifiers both to resolve the source_substance to a substance and potentially to link to an external resource

A Source Substance (Record) Consists of the following fields:
record_id = a varchar id minted similarly to the DTXSID and DTXCID, but starting with DTXRID
external_id = String (Less than 500 characters, required field)
Mapped Substance = A substance (issue #90) (optional)
Mapping score = Float (optional)
Mapping message = String (Less than 500 characters, optional)
Mapping is_validated = boolean 
A List = the list this is a member of (issue #174) (required)

**Acceptance Criteria**
A test to show when a source substance is created it works properly...

**Comment by michael-barbour** [comment]
@cmgrulke The name SourceSubstance seems like a confusing name for this model.  The name current feels like it implies a connection between source (#89) and substance (#90).

You added, in parenthesis, (Record) as a clarification.  Would it be alright if we simply named this model "Record" or perhaps "ListRecord" to emphasize that this model belongs to a List (#174)?

**Comment by cmgrulke** [comment]
Yup, I am good with both 1 and 2
