### ISSUE TITLE
Source Substance Identifier Model

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#177]
**As a** product owner
**I want** to be able to store all the identifiers associated with a member of a source list
**So that** I can use those identifiers both to resolve the source_substance to a substance and potentially to link to an external resource

A Source Substance Identifier Consists of the following fields:
Source Substance= the member of the list this identifier is associated with (issue #175) (required)
identifier = TEXT (required)
Identifier_Type = An identifier type controlled vocabulary (issue #176) (optional)
identifier_label  = String (Less than 100 characters, required field)

**Acceptance Criteria**
A test to show when a source substance identifier is created it works properly...

**Comment by michael-barbour** [comment]
#175 has had the model name updated to `Record` to hopefully avoid confusion.  This should probably be named `RecordIdentifier` to follow with that naming schema.
