### ISSUE TITLE
List Type model

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#178]
**As a** product owner
**I want** to be able to store list types as a controlled vocabulary of the types of lists.
**So that** I can better organize lists

A identifier type consists of:
- Name = String (Less than 50 character, url safe, unique, required field)
- Label = String (Less than 100 characters, unique, required field)
- Short Description = String (Less than 500 characters, required field)
- Long Description = TEXT (required field)

**Acceptance Criteria**
A test to show when a list type is created it works properly...

**Comment by michael-barbour** [comment]
Cleared myself as assignee to take #176.  176 was pointed high specifically for building the List app.
