### ISSUE TITLE
New Developer Setup Documentation

### ISSUE THREAD

**Issue by dmlyons2** [Chemical-Curation/chemcurator_django#21]
**As a** new developer
**I want** to be able to get the dev environment up and running quickly
**So that** I can quickly start contributing to the team

**Acceptance Criteria:**
A wiki page with instructions on how to get started with the app

**Comment by mcovalt** [comment]
The developer setup documentation was added by @debboutr [here](https://github.com/Chemical-Curation/chemcurator_django/wiki/Developer-Setup).

It is very thorough!

Much of the setup work involves getting PostgreSQL up. Once we have automated testing with PostgreSQL and if we keep the code database-agnostic, we can probably drop PostgreSQL in the development environment and instead use SQLite. Until then, we'll definitely need PostgreSQL while developing.
