### ISSUE TITLE
add updated_at/updated_by to serializers

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#220]
**As a** anonymous user
**I want** to see the 'common info' when I get back a resource
**So that** I can tell when it was last changed and who made that change

**Acceptance Criteria**
All apis include the common info (like updated_at, updated_by) when serializing.

**Comment by kdionisio** [comment]
Also include created at and created by.

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1NTfKkVbz94ToFTcNKY89P8TV4f_5m0t0/view?usp=sharing)
