### ISSUE TITLE
substance display and preferred name interplay

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#225]
**As a** curator
**I want to** not put in display names if it should be the same as the preferred name
**So that** I don't have to manage redundant information

`POST https://api.chemreg.epa.gov/substances`
`PATCH https://api.chemreg.epa.gov/substances/{id}`
`GET https://api.chemreg.epa.gov/substances`
`GET https://api.chemreg.epa.gov/substances/{id}`

**Acceptance Criteria:**
- display_name is not required (is nullable)
- If the display name is stored as null, the api on get should return the preferred_name as the display_name on GET requests.

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/16F_goU3tmtKZhbvKZZlfLfAt7N7qGtI7/view?usp=sharing)

**Comment by michael-barbour** [comment]
Example of newly functioning POST with null `display_name`.

[225-substance-display-name.postman_collection.zip](https://github.com/Chemical-Curation/chemcurator_django/files/5373879/225-substance-display-name.postman_collection.zip)
