### ISSUE TITLE
record relationship to record identifiers

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#228]
**As a** user
**I want to** receive a link to the record identifiers for a record as a relationship
**So that** I can easily navigate to those record identifier resources

`GET https://api.chemreg.epa.gov/records`
`GET https://api.chemreg.epa.gov/records/{id}`

**Acceptance Criteria:**
- there is a relationship link to record identifiers in the record resource

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1WFpVK5hUHeNc_Nx7Z6gfedi0ERPuIxxH/view?usp=sharing)
