### ISSUE TITLE
rid initialized at 20,000,000

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#229]
**As a** user
**I want** the rid in this new implementation of ChemReg to start at 20000000
**So that** there are no conflicts with rids minted in old ChemReg

`POST https://api.chemreg.epa.gov/records`

**Acceptance Criteria:**
- initialize the incremented integer used for RID creation to 20000000

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1464Av12UemCew4CdaAEmmSVfY2cZIEtq/view?usp=sharing)
