### ISSUE TITLE
list html errors are rejected

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#230]
**As a** user
**I want to** have descriptions for lists (short_description and long description) validated not corrected
**So that** I am warned of problems in submitted description fields and can be sure that what is recorded always matches with my desired description

`POST https://api.chemreg.epa.gov/list`
`PATCH https://api.chemreg.epa.gov/list/{id}`

**Acceptance Criteria:**
- short and long description are not corrected to proper html when created or edited.  
- if short and long descriptions are not valid html, the patch or post is rejected and an error message is provided to the user.
- provide back to user the potential corrected html

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1vQqgsruCjTji-vdx3v9cLMyifB0io9kh/view?usp=sharing)
