### ISSUE TITLE
name/synonym restrictive validation bug on synonym PATCH

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#236]
**Describe the bug**
Validation as specified in issue #145 is not working as expected when PATCHing a synonym associated with a restrictive synonymQuality

**To Reproduce**
1. Create a synonym that is linked to a restrictive synonym quality
2. PATCH that synonym and change only the qcNote
3. See the error stating the synonym.identifier value already exists (which of course it does because this record is a restrictive synonym)

**Expected behavior**
If I am PATCHing a synonym that is already associated with a restrictive synonym quality, changing only the qcNote, source, or synonymType do not need to check if the synonym.identifier exists as a restrictive synonym.  In the case above the QcNote should update as it will not create a duplicate in the restrictive identifier set.

**Comment by michael-barbour** [comment]
I've attached a postman collection as well as a folder with 3 curl requests.

**Comment by michael-barbour** [comment]
I've attached a postman collection as well as a folder containing the same 3 curl requests.

To replicate:

[145 bug.postman_collection.zip](https://github.com/Chemical-Curation/chemcurator_django/files/5197813/145.bug.postman_collection.zip)
[145 bug curl.zip](https://github.com/Chemical-Curation/chemcurator_django/files/5197850/145.bug.curl.zip)

**Comment by dmlyons2** [comment]
@cmgrulke let's chat about this after sprint review and update the def of done.
