### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by dmlyons2** [Chemical-Curation/chemcurator_django#24]
**As a** *product owner*
**I want** the ability to add users to the application and assign them roles. The only role is admin. 
**So that** I can control who is using the application.

Acceptance Criteria:
I can go to https://admin.chemreg.epa.gov and login 
I do not want to be able to edit models within the admin application
I do want to be able to add users and assign those users role(s)
~~Ensure users are in a separate schema then chemreg data~~

~~All chemistry needs to be in its own database - and admin in its database.~~

**Comment by debboutr** [comment]
[multiple DBs](https://docs.djangoproject.com/en/2.2/topics/db/multi-db/#exposing-multiple-databases-in-django-s-admin-interface)

**Comment by dmlyons2** [comment]
This functionality is already working in the app.
