### ISSUE TITLE
Synonym Resolution

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#248]
**As a** researcher
**I want to** be able to able to find a substance using a name or casrn that exists in the synonyms rather than the substance model
**So that** I can find the chemical I am interested in

`GET https://api.chemreg.epa.gov/search?identifier=$$$$$$$`

Acceptance Criteria:
- If the searched identifier matches a synonym.identifier, those substances are added to the list of the dtxsids returned.

**Comment by jtumkur** [comment]
Search resolver for Synonym
