### ISSUE TITLE
Use the cid as the primary key of the compound table

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#249]
As a *researcher*
I want *the compound resource to use the cid as its resource id (by making it the primary key in the table)*
So that *crafting a the url to use the api is easier*

Acceptance Criteria:
Change the primary key for the compound table to the cid
Fix all the tests that will be broken by this change
Will also need to look at vuejs to see if an update is needed there.

Test:

**Comment by jtumkur** [comment]
249, 250, 251
CID, SID from the tables.
Approved
