### ISSUE TITLE
Use the name field as the primary key for all controlled vocabularies

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#252]
As a *researcher*
I want *the controlled vocabulary resource to use the name field as their resource ids (by making it the primary key in the table)*
So that *crafting a the url to use the api is easier*

Acceptance Criteria:
Change the primary key for all controlled vocabulary tables to the name
Fix all the tests that will be broken by this change
Will also need to look at vuejs to see if an update is needed there

Test:

**Comment by debboutr** [comment]
chris, just to be sure, these are the models that we are considering ControlledVocabularies...
```
QCLevelsType
Source
SubstanceType
SynonymType
SynonymQuality
RelationshipType
AccessibilityType
IdentifierType
ListType
QueryStructureType
```
would there be others, like List? or other models that use `name` and `label`?

**Comment by cmgrulke** [comment]
The ones listed are the ones I want.  Do not include lists or external contact in this ticket please.

**Comment by scaduto** [comment]
> The ones listed are the ones I want. Do not include lists or external contact in this ticket please.

:+1:
