### ISSUE TITLE
substance name regexp accepts "*" and "_"

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#289]
As a *curator*
I want *additional characters to be acceptable in names*
So that *I can properly name things when registering them*

Acceptance Criteria:
For both the display and preferred name
- Accept an asterisk "*"
- Accept an underscore "_"

Test:

**Comment by stevenhausman-gdit** [comment]
Changed to raw to remove escape characters.
Took a quick inexpert look at tests and I don't think I need to modify them.
Can I get some handholding on commit/PR/'swimlane' changes/migrations stuff?
Thanks!
`preferred_name_regex = r"^[a-zA-Z0-9 =<>\-\*_':.,^%&\/{}[\]]{3,}$"`
`display_name_regex = r"^[a-zA-Z0-9 =<>\-\*_':.,^%&\/{}[\]]{3,}$"`

![regex](https://user-images.githubusercontent.com/74921039/101410548-83671280-38ad-11eb-9206-9d3a03f41d5f.png)
![saved](https://user-images.githubusercontent.com/74921039/101410569-895cf380-38ad-11eb-8cbb-e9cd9445031d.png)

**Comment by stevenhausman-gdit** [comment]
I see some tests in #277, will attempt similar
