### ISSUE TITLE
Synonym type should be nullable

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#293]
Can you create a bug ticket for a bug I found working on ticket #99?  Looks like when a synonym is created through the API it cannot be created with a null "Synonym Type" due to a bug in our validation code for synonyms.  Our code returns a 500 error.

**Comment by jtumkur** [comment]
293 closed due to duplicate of 295

**Comment by jtumkur** [comment]
#295
