### ISSUE TITLE
Create defined compound with v2000 molfile

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#37]
**As a** researcher
**I want** to be able to create defined compounds with a v2000 molfile
**So that I** don't have to worry about doing chemical structure format conversions

**Request Example**
`POST https://api.chemreg.epa.gov/defined-compounds/`

**Acceptance Criteria:**
I can POST a v2000 rather than a v3000 molfile to the defined compounds endpoint.  The application will convert the v2000 to v3000 format and provide me back the same responses I would get if I submitted a v3000 molfile.  If the v2000 cannot be converted to v3000 format, the input is invalid (415 or 400?) (Message: "Supplied v2000 cannot be converted to v3000 molfile.").

**Test:**

**Comment by debboutr** [comment]
do we ever want to keep the original string that was used to post the compound in this case or in the smiles case. It seems that either of these will use `Indigo` to write out the V3000 format, but once loaded we won't the string that originally made the compound. In the v3000 case we are just storing the original string if it validates. I'm pretty sure that if a V3000 compound is loaded into Indigo and then written from Indigo has the potential to be slightly different in it's format coming from Indigo...
```
In [1]: from indigo import Indigo                                                                                         

In [2]: indigo = Indigo()                                                                                                 

In [3]: indigo.setOption("molfile-saving-mode", "3000")                                                                   

In [4]: struct = indigo.loadStructure(structureStr="\n  Mrv1805 09121917092D          \n\n  0  0  0     0  0            99
   ...: 9 V2000  \nM  V30 BEGIN CTAB\nM  V30 COUNTS 26 28 0 0 0\nM  V30 BEGIN ATOM\nM  V30 1 O 5.535 -11.0776 0 0\nM  V30 
   ...: 2 C 4.9086 -9.6708 0 0\nM  V30 3 C 3.377 -9.5098 0 0\nM  V30 4 C 2.4718 -10.7557 0 0\nM  V30 5 C 0.9403 -10.5947 0
   ...:  0\nM  V30 6 C 0.3139 -9.1879 0 0\nM  V30 7 F -1.2177 -9.0269 0 0\nM  V30 8 C 1.2191 -7.942 0 0\nM  V30 9 C 2.7506
   ...:  -8.1029 0 0\nM  V30 10 C 5.8138 -8.4249 0 0\nM  V30 11 C 7.3453 -8.5859 0 0\nM  V30 12 C 8.2505 -7.34 0 0\nM  V30
   ...:  13 N 9.7821 -7.5009 0 0\nM  V30 14 C 10.6873 -6.2551 0 0\nM  V30 15 C 12.2188 -6.416 0 0\nM  V30 16 C 12.8452 -7.
   ...: 8229 0 0\nM  V30 17 O 14.1219 -6.9617 0 0\nM  V30 18 C 13.915 -8.9307 0 0\nM  V30 19 C 15.4092 -8.5581 0 0\nM  V30
   ...:  20 C 16.479 -9.6659 0 0\nM  V30 21 C 16.0545 -11.1462 0 0\nM  V30 22 C 14.5603 -11.5188 0 0\nM  V30 23 C 13.4905 
   ...: -10.411 0 0\nM  V30 24 C 17.1243 -12.254 0 0\nM  V30 25 C 11.94 -9.0688 0 0\nM  V30 26 C 10.4085 -8.9078 0 0\nM  V
   ...: 30 END ATOM\nM  V30 BEGIN BOND\nM  V30 1 2 1 2\nM  V30 2 1 2 3\nM  V30 3 2 3 4\nM  V30 4 1 4 5\nM  V30 5 2 5 6\nM 
   ...:  V30 6 1 6 7\nM  V30 7 1 6 8\nM  V30 8 2 8 9\nM  V30 9 1 3 9\nM  V30 10 1 2 10\nM  V30 11 1 10 11\nM  V30 12 1 11 
   ...: 12\nM  V30 13 1 12 13\nM  V30 14 1 13 14\nM  V30 15 1 14 15\nM  V30 16 1 15 16\nM  V30 17 1 16 17\nM  V30 18 1 16 
   ...: 18\nM  V30 19 2 18 19\nM  V30 20 1 19 20\nM  V30 21 2 20 21\nM  V30 22 1 21 22\nM  V30 23 2 22 23\nM  V30 24 1 18 
   ...: 23\nM  V30 25 1 21 24\nM  V30 26 1 16 25\nM  V30 27 1 25 26\nM  V30 28 1 13 26\nM  V30 END BOND\nM  V30 END CTAB\n
   ...: M  END\n")                                                                                                        

In [5]: struct.molfile()                                                                                                  
Out[5]: '\n  -INDIGO-04222016452D\n\n  0  0  0  0  0  0  0  0  0  0  0 V3000\nM  V30 BEGIN CTAB\nM  V30 COUNTS 0 0 0 0 0\n
M  V30 BEGIN ATOM\nM  V30 END ATOM\nM  V30 BEGIN BOND\nM  V30 END BOND\nM  V30 END CTAB\nM  END\n'
```

Should we always be using Indigo to writeout the molfile that is kept in the `molfile_v3000` field of the compound?

**Comment by cmgrulke** [comment]
Clarified in discussion on slack.  This is the key statement from the discussion.

Chris Grulke  1:01 PM
Basically, I want our structure string for a defined compound to be a v3000 molfile.  If the user provides a v3000 molfile, we store it (as long as it validates).  If they provide a different structural string, we change it to a v3000 molfile string and use that.
