### ISSUE TITLE
defined compound model

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#4]
As a product owner

I would like to store a defined compound
So that I can use it in my application

A Defined Compound is an extension of a Compound and consists of:

- ID (from the compound model)
- molfile_v3000: Text Field (required field) (acts as the definitive structure string from the compound model)
- inchikey: string (less than 30 characters) (required field)

**Acceptance Criteria:**
A test to show when a compound is created it has an id, molfile, and inchikey

**Comment by dmlyons2** [comment]
@cmgrulke - Please provide a few examples of inchi keys and molfile_v3000 for our fixture data.

**Comment by cmgrulke** [comment]
example molfile:
`
  Mrv1805 09121917092D          

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 26 28 0 0 0
M  V30 BEGIN ATOM
M  V30 1 O 5.535 -11.0776 0 0
M  V30 2 C 4.9086 -9.6708 0 0
M  V30 3 C 3.377 -9.5098 0 0
M  V30 4 C 2.4718 -10.7557 0 0
M  V30 5 C 0.9403 -10.5947 0 0
M  V30 6 C 0.3139 -9.1879 0 0
M  V30 7 F -1.2177 -9.0269 0 0
M  V30 8 C 1.2191 -7.942 0 0
M  V30 9 C 2.7506 -8.1029 0 0
M  V30 10 C 5.8138 -8.4249 0 0
M  V30 11 C 7.3453 -8.5859 0 0
M  V30 12 C 8.2505 -7.34 0 0
M  V30 13 N 9.7821 -7.5009 0 0
M  V30 14 C 10.6873 -6.2551 0 0
M  V30 15 C 12.2188 -6.416 0 0
M  V30 16 C 12.8452 -7.8229 0 0
M  V30 17 O 14.1219 -6.9617 0 0
M  V30 18 C 13.915 -8.9307 0 0
M  V30 19 C 15.4092 -8.5581 0 0
M  V30 20 C 16.479 -9.6659 0 0
M  V30 21 C 16.0545 -11.1462 0 0
M  V30 22 C 14.5603 -11.5188 0 0
M  V30 23 C 13.4905 -10.411 0 0
M  V30 24 C 17.1243 -12.254 0 0
M  V30 25 C 11.94 -9.0688 0 0
M  V30 26 C 10.4085 -8.9078 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 2 1 2
M  V30 2 1 2 3
M  V30 3 2 3 4
M  V30 4 1 4 5
M  V30 5 2 5 6
M  V30 6 1 6 7
M  V30 7 1 6 8
M  V30 8 2 8 9
M  V30 9 1 3 9
M  V30 10 1 2 10
M  V30 11 1 10 11
M  V30 12 1 11 12
M  V30 13 1 12 13
M  V30 14 1 13 14
M  V30 15 1 14 15
M  V30 16 1 15 16
M  V30 17 1 16 17
M  V30 18 1 16 18
M  V30 19 2 18 19
M  V30 20 1 19 20
M  V30 21 2 20 21
M  V30 22 1 21 22
M  V30 23 2 22 23
M  V30 24 1 18 23
M  V30 25 1 21 24
M  V30 26 1 16 25
M  V30 27 1 25 26
M  V30 28 1 13 26
M  V30 END BOND
M  V30 END CTAB
M  END
` 
inchikey: AGAHNABIDCTLHW-UHFFFAOYSA-N
