### ISSUE TITLE
ill-defined compound model

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#5]
As a product owner

I would like to store a defined compound
So that I can use it in my application

A Ill-Defined Compound is an extension of a Compound and consists of:

- ID (from the compound model)
- mrvfile: Text Field (required field) (acts as the definitive structure string from the compound model)
- query_structure_type: embedded sub-entity many to one ill-defined

**Acceptance Criteria:**
A test to show that when a Ill-Defined compound is registered, it has an id, mrvfile, and query_structure_type

**Comment by cmgrulke** [comment]
example mrvfile:
`<cml><MDocument><MChemicalStruct><molecule molID="m1"><atomArray><atom id="a1" elementType="C" x2="-1.1102230246251565e-16" y2="0"/><atom id="a2" elementType="O" x2="1.54" y2="1.1102230246251565e-16" lonePair="2"/></atomArray><bondArray><bond atomRefs2="a1 a2" order="2" id="b1"/></bondArray></molecule></MChemicalStruct><MElectronContainer occupation="0 0" radical="0" id="o1"><MElectron atomRefs="m1.a2" difLoc="0.0 0.0 0.0"/><MElectron atomRefs="m1.a2" difLoc="0.0 0.0 0.0"/></MElectronContainer><MElectronContainer occupation="0 0" radical="0" id="o2"><MElectron atomRefs="m1.a2" difLoc="0.0 0.0 0.0"/><MElectron atomRefs="m1.a2" difLoc="0.0 0.0 0.0"/></MElectronContainer></MDocument></cml>`

**Comment by dmlyons2** [comment]
Test from chemcurator_django

**Comment by dmlyons2** [comment]
@mwfrost Test to slack
