### ISSUE TITLE
ui_curator Role Authorization API Endpoint

### ISSUE THREAD

**Issue by dmlyons2** [Chemical-Curation/chemcurator_django#52]
**As a** UI Curator
**I want an** authorization api
**So that** so that I can securely access parts of the ChemReg UI application using a token such as JWT or baked in TokenAuthentication with DWF.

Acceptance Criteria:
* Endpoint for authorization 
* Make token expiration time an environment variable - the default of 15 minutes

Test:

**Comment by mcovalt** [comment]
> Make token expiration time an environment variable - the default of 15 minutes

Does this mean the user will need to login every 15 minutes? Or the session expires when inactive for 15 minutes?
