### ISSUE TITLE
Synonym_type Model

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#56]
**As a** Admin
**I want** to be able to store a controlled vocabulary for Synonym types
**So that** I can tag synonyms with a type when I create them

A synonym_type consists of:
- Name = String (Less than 50 character, url safe, unique, required field)
- Label = String (Less than 100 characters, unique, required field)
- Short Description = String (Less than 500 characters, required field)
- Long Description = TEXT (required field)
- Validation Regular Expression = String (not required)  <---- to be discussed in grooming
- score modifier = Float (default 0) <---- to be discussed in grooming

**Acceptance Criteria**
A test to show when a Synonym type is created it has the name, label, and description fields

**Comment by mwfrost** [comment]
The Synonym object model should have a method for checking its string against the synonym type's regex

**Comment by mcovalt** [comment]
Closed with PR #132
