### ISSUE TITLE
Synonym Quality Model

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#62]
**As a** Admin
**I want** to be able to store a controlled vocabulary for Synonym Qualities
**So that** I can tag synonyms with a quality level when I create them

A synonym_quality consists of:
- Name = String (Less than 50 character, url safe, unique, required field)
- Label = String (Less than 100 characters, unique, required field)
- Short Description = String (Less than 500 characters, required field)
- Long Description = TEXT (required field)
- score_weight = Float (default 1.0) greater than 0
- is_restrictive = Boolean

**Acceptance Criteria**
A test to show when a Synonym quality is created it has the name, label, and description fields

**Comment by debboutr** [comment]
quick check for tests here, should this field have a default for `is_restrictive`? or just be `None` upon creation?

**Comment by cmgrulke** [comment]
I think it is cleanest if `is_restrictive` defaults to `false` but you could also leave it as `none` and then treat `none` the same as false.
