### ISSUE TITLE
CRUD Query Structure Type API - Delete modification

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#70]
**As a** admin
**I want** to be able to "delete" a Query Structure Type without the information on that type being lost
**So that** I can delete a type in use as a sub-resource for a ill-defined compound

**Request Example**
`DELETE https://api.chemreg.epa.gov/query-structure-type/{id}`

**Acceptance Criteria:**
As an admin, when I DELETE a query structure type, it really just deprecates it. That query structure type will continue to exist in the database.  It will still show up in a listing of all query structure types, but will be tagged as not for use.  Ill-defined-compound resources that are submitted with that query structure type as a sub-resource will be rejected with an informative error message like "The Query Structure Type submitted for this compound is no longer supported."  

**Test:**

**Comment by debboutr** [comment]
do we need to be concerned with the instances where a QueryStructureType is deprecated but IllDefined compounds point to it? should those be reverted back to using the default `ill-defined` QST? Or should they just remain as they are, pointing to a deprecated QST?

**Comment by cmgrulke** [comment]
They should remain as they are, pointing to the deprecated QST.  If someone attempts to PATCH that ill-defined compound, ideally, they would get an error that the QST for that record is not valid, (similar to what happens if someone tries a POST with a deprecated QST).  However, that may require a separated ticket since it wasn't clearly defined in the acceptance criteria here.
