### ISSUE TITLE
Defined-compound detail view

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#71]
**As a** researcher
**I want** to get the molecular weight, molecular formula, smiles, and inchikey when I GET a single resource for a compound
**So that I** don't have to generate them myself

**Request Example**
`GET https://api.chemreg.epa.gov/defined-compounds/DTXCID3948157

**Acceptance Criteria:**
When I GET a single defined compound resource, that resource has the following additional fields in the returned json: molecular weight, molecular formula, smiles, and calculated_inchikey.  All are calculated based on the v3000 molfile being returned.

**Test:**

**Comment by debboutr** [comment]
hey @cmgrulke , is the `calculated_inchikey` somehow different from the `inchikey` that we have calculated when creating the compound? I would think we already have this attribute in the detail view. 

Also, is this the kind of thing that you want to see for molecular formula?
`"C22 H26 F N O2"`
or would the percent of mass composition of each atom be better?
`"C 74.34 H 7.37 F 5.34 N 3.94 O 9.00"`

**Comment by cmgrulke** [comment]
So, the calculated inchikey is important for two use cases.  First, when I put old compound data into the API, I will be providing the InChIKey from my old system.  Then I will iterated through the records using the api and to see where the inchikey is changed from what I had in the old database. Complicated logic and in some instances manual decision making might be required to clean up the mess.  I would rather have to tools in the api to address that myself rather than have to try to ticket the data cleanup. 

Similarly InChI has revisions and the implementations of InChI in Indigo or other toolkits can cause minor InChI/InChIKey changes between versions.  I am really looking forward to InChI 2.0.  However, if I want our InChIKey generator updated, I will be ticketing the alteration of the API code to use the newest toolkit/InChI packages while leaving the data in the InChIKey column in the database unchanged.  It will fall to me or another chemical curation expert can decide how to resolve the changes.

Essentially, what I am saying is that InChIKey stored in the database is allowed (and in some cases expected) to be stale!  The calculated inchikey will never be stale.  In most cases, they will be exactly the same, but when they are not it will fall to a chemical curator to fix the data rather than to the dev team.

**Comment by cmgrulke** [comment]
For the molecular formula, I expect this: 
`C22 H26 F N O2`
