### ISSUE TITLE
Implement JSON:API

### ISSUE THREAD

**Issue by dmlyons2** [Chemical-Curation/chemcurator_django#77]
**As a** developer
**I want** the API logic to adhere to the JSON:API specification
**So that** documentation can be effectively generated with no unique cases, the API can be accessed in a standardized way, and design criteria of all endpoints can be constrained to the allowed methods of the specification.  

**Acceptance Criteria:**
Use the django-rest-framework-json-api package to implement the specification. All endpoints should respect the JSON:API specification entirely.
If a feature is not implemented in the django-rest-framework-json-api package, adjust the API design to allow the use of the package. Make a note of this incompatibility and suggest a ticket to patch in the new feature to the django-rest-framework-json-api package.
**Test:**
Ensure all endpoints use this specification. There is no need to test each model view individually as the package is well tested. If a bug appears in the package, a new test demonstrating this bug and a fix for the bug should be submitted to the package maintainers.

**Comment by mwfrost** [comment]
For reference and discussion, I composed this example of how a Factotum API response would change under the new standard:
```
{
chemical_id: "DTXSID9022528",
component: null,
lower_weight_fraction: "0.125000000000000",
central_weight_fraction: null,
upper_weight_fraction: "0.250000000000000",
ingredient_rank: null,
rid: "DTXRID002",
document: 156051,
products: [
1868
]
},
​```
would become something like
​```
{
  "type": "composition",
  "id": "1", (maybe this would be the RawChem pk?)
  "attributes": {
    "component": null,
	"lower_weight_fraction": "0.125000000000000",
	"central_weight_fraction": null,
	"upper_weight_fraction": "0.250000000000000",
	"ingredient_rank": null,
	"rid": "DTXRID002",
  },
  "relationships": {
    "document": {
      "links": {
        "self": "http://127.0.0.1:8001/composition/DTXRID002/relationships/document/156051",
        "related": "http://127.0.0.1:8001/composition/DTXRID002/documents/156051"
      },
      "data": { "type": "document", "id": "156051" }
    },
    "product": {
      "links": {
        "self": "http://127.0.0.1:8001/composition/DTXRID002/relationships/product/1868",
        "related": "http://127.0.0.1:8001/composition/DTXRID002/products/1868"
      },
      "data": { "type": "product", "id": "1868" }
    }
  },
  "links": {
    "self": "http://127.0.0.1:8001/composition/DTXRID002"
  }

```
