### ISSUE TITLE
substance model

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#90]
**As a** Admin
**I want** to be able to store a substance
**So that** I can document chemical concepts

A substance consists of:
Substance id = string (e.g. DTXSID) (generated)
preferred_name = string (255) (required) (unique)
display_name = string (255) (required) (unique)
source (a source resource... issue #89 ) (required)
substance_type (a substance-type resource ... issue #86 ) (required)
qc_level (a qc-level resource... issue #87 ) (required)
a substance description = string (1024)
a public qc note = string (1024)
a private qc note = string (1024)
an associated compound (a compound resource)
casrn = String (unique)
a set of synonyms (many synonym resources ... issue #88 )
a set of substance histories (many substance history resources ... issue #92)

**Acceptance Criteria**
A test to show when a substance is created it works properly...

**Comment by AScaduto** [comment]
@cmgrulke It looks like this issue is being blocked by #92

**Comment by michael-barbour** [comment]
Reversed the blocking order.  This ticket now blocks #92 as opposed to being blocked by #92.

**Comment by michael-barbour** [comment]
Hey @cmgrulke, I have a few questions to make sure I'm creating this model the way it needs to be made.

> Substance id = string (e.g. DTXSID) (generated)

Is this SID constructed using the same sequence as CID?
Also, am I correct to call this an "sid"?  Compounds have "cid"s so I'd like to mimic that naming schema.

Regarding the generation of SIDs:
Looks like CIDs start at 2,000,000 and increment.  Am I starting at the same point with the sequence and are the numbers going be reused?  Are DTXSIDxxx02000000 and DTXCID_02000000 both valid ids in the same database (_ is the checksum).

> a set of synonyms (many synonym resources ... issue #88 )

Are these synonyms going to be many to many or one to many?

Given a synonym would that correspond to only one substance or are there cases where a single synonym can refer to many different substances.

> a set of substance histories (many substance history resources ... issue #92)

I'm assuming one to many as it would make the most sense.  One Substance can have many SubstanceHistory records

> casrn

Can you give me a quick description of what this is for the documentation?  It might help onboard future developers.

**Comment by cmgrulke** [comment]
Ok, so let me give it a try.

The DTXSID should use a different sequence from the CID, but be generated using the same logic.  DTXCID*02000000 and DTXSID*02000000 should both end up as valid ids for a compound and substance respectively.  Please also start at 2000000 so that newly minted ids will not have conflicts with ids that already exist in the old system.

One to many for substances to synonyms. (There are cases where the same synonym.identifier value could exist under two different susbstances, but the substance type, source, and quality fields for those synonyms are likely to be different.

So, substance histories don't exist yet, but they were originally intended to capture the revisions of a substance record.  This is now unlikely to make it into the MVP release of the product, so we will need to come back to history and versioning later.

A CAS-RN is a CAS registry number.  It is an identifier from the CAS Registry (https://www.cas.org/support/documentation/chemical-substances) for a chemical substance.  CAS Registry is a closed database system that cannot be queries in batch, otherwise much of the work we are doing here likely would be unnecessary. However, CAS-RNs are the most commonly used substance identifier in the world after names.
